@baseUrl = http://localhost:5432/api/v1/news


GET {{baseUrl}}/news

POST {{baseUrl}}/news
Content-Type: application/json

{
    "title": "news1",
    "content": "content1",
    "author": "author1"
}


