openapi: 3.0.0
info:
  title: News API
  description: API para gerenciamento de notícias
  version: 1.0.0
servers:
  - url: http://localhost:5432/api/v1/news
paths:
  /news:
    get:
      summary: Retorna todas as notícias
      responses:
        '200':
          description: Lista de notícias
    post:
      summary: Cria uma nova notícia
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/News'
      responses:
        '201':
          description: Notícia criada
  /news/{id}:
    get:
      summary: Retorna uma notícia por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalhes da notícia
    put:
      summary: Atualiza uma notícia por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/News'
      responses:
        '200':
          description: Notícia atualizada
    delete:
      summary: Deleta uma notícia por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Notícia deletada
components:
  schemas:
    News:
      type: object
      required:
        - title
        - content
        - author
      properties:
        title:
          type: string
        content:
          type: string
        author:
          type: string
